name: Terraform PR Check

on:
  pull_request:
    paths:
      - 'envs/dev/**/*'
      - '*.tf'
      - '.github/workflows/**'

permissions:
  contents: read
  pull-requests: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
  WORKING_DIR: "."
  TF_CLI_ARGS_init: '-backend-config=envs/dev/state.config'
  TF_CLI_ARGS_plan: '-var-file=envs/dev/terraform.tfvars'

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v2
        id: github-app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout source
        uses: actions/checkout@v5
        with:
          token: ${{ steps.github-app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Run Terraform Plan
        uses: c0x12c/gh-actions-terraform-workflows/actions/terraform-plan@v1
        env:
          TF_CLI_ARGS_init: ${{ env.TF_CLI_ARGS_init }}
          TF_CLI_ARGS_plan: ${{ env.TF_CLI_ARGS_plan }}
        with:
          aws_region: ${{ env.AWS_REGION }}
          aws_role: ${{ env.AWS_ROLE_TO_ASSUME }}
          github_token: ${{ steps.github-app-token.outputs.token }}
          environment: dev
          python_version: '3.12'
          secret_filter: 'app-dev'
          terraform_version: '1.10.5'
          working_dir: ${{ env.WORKING_DIR }}
