name: Dev - Check Pull Request

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  actions: write # required for cache write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 18.18.2
  # TODO: Update corresponding NodeJS version and matching .env values
  # Example .env values:
  # VITE_SERVICE_PLATFORM_API_URL: ${{ vars.VITE_SERVICE_PLATFORM_API_URL_DEV }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App Token
        id: github-app-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ vars.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          token: ${{ steps.github-app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Run install
        run: yarn install --frozen-lockfile

      - name: Run Linters
        run: yarn lint

      - name: Run Tests
        run: yarn test --coverage --watchAll=false
