name: 'Setup Frontend Environment'
description: 'Combined setup: GitHub auth, AWS credentials, and Node.js environment'
inputs:
  app_id:
    description: 'GitHub App ID'
    required: true
  private_key:
    description: 'GitHub App private key'
    required: true
  fetch_depth:
    description: 'Git fetch depth'
    required: false
    default: '3'
  ref:
    description: 'Git ref to checkout'
    required: false
    default: ''
  aws_role_to_assume:
    description: 'AWS IAM role ARN to assume'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
  node_version:
    description: 'Node.js version'
    required: true
  package_manager:
    description: 'Package manager (yarn, npm, pnpm)'
    required: false
    default: 'yarn'

runs:
  using: 'composite'
  steps:
    # === GitHub Authentication ===
    - name: Generate GitHub App Token
      id: github-app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.private_key }}
        owner: ${{ github.repository_owner }}

    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch_depth }}
        token: ${{ steps.github-app-token.outputs.token }}
        ref: ${{ inputs.ref != '' && inputs.ref || github.head_ref || github.ref }}
        persist-credentials: false

    # === Node.js Setup ===
    - name: Set Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: ${{ inputs.package_manager }}

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.package_manager }}" = "yarn" ]; then
          yarn install --frozen-lockfile
        elif [ "${{ inputs.package_manager }}" = "pnpm" ]; then
          pnpm install --frozen-lockfile
        else
          npm ci
        fi

    # === AWS Credentials ===
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_role_to_assume }}
        role-session-name: gh-actions
        aws-region: ${{ inputs.aws_region }}
