name: 'Setup Environment'
description: 'Combined setup: GitHub auth, AWS credentials, and language environment'
inputs:
  app_id:
    description: 'GitHub App ID'
    required: true
  private_key:
    description: 'GitHub App private key'
    required: true
  fetch_depth:
    description: 'Git fetch depth'
    required: false
    default: '3'
  ref:
    description: 'Git ref to checkout'
    required: false
    default: ''
  aws_role_to_assume:
    description: 'AWS IAM role ARN to assume'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
  language:
    description: 'Language: java-kotlin or python'
    required: true
  java_version:
    description: 'Java version (for java-kotlin)'
    required: false
    default: '17'
  python_version:
    description: 'Python version (for python)'
    required: false
    default: '3.11'
  artifactory_url:
    description: 'Artifactory URL (for java-kotlin)'
    required: false
    default: ''
  artifactory_username:
    description: 'Artifactory username (for java-kotlin)'
    required: false
    default: ''
  aws_code_artifact_domain:
    description: 'AWS Code Artifact domain (for java-kotlin)'
    required: false
    default: ''
  aws_account_id:
    description: 'AWS account ID'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    # === GitHub Authentication ===
    - name: Generate GitHub App Token
      id: github-app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.private_key }}
        owner: ${{ github.repository_owner }}

    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch_depth }}
        token: ${{ steps.github-app-token.outputs.token }}
        ref: ${{ inputs.ref != '' && inputs.ref || github.head_ref || github.ref }}
        persist-credentials: false

    # === AWS Credentials ===
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_role_to_assume }}
        role-session-name: gh-actions
        aws-region: ${{ inputs.aws_region }}

    # === Java/Kotlin Setup ===
    - name: Install AWS CLI
      if: inputs.language == 'java-kotlin' && inputs.aws_code_artifact_domain != ''
      shell: bash
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version

    - name: Write gradle.properties
      if: inputs.language == 'java-kotlin' && inputs.artifactory_url != '' && inputs.aws_code_artifact_domain != ''
      shell: bash
      run: |
        mkdir -p ~/.gradle
        cat <<EOF > ~/.gradle/gradle.properties
        artifactRegistryMavenReleaseUrl=${{ inputs.artifactory_url }}
        artifactRegistryMavenUsername=${{ inputs.artifactory_username }}
        artifactRegistryMavenPassword=$(aws codeartifact get-authorization-token --domain ${{ inputs.aws_code_artifact_domain }} --domain-owner ${{ inputs.aws_account_id }} --region ${{ inputs.aws_region }} --query authorizationToken --output text)
        EOF

    - name: Set up JDK
      if: inputs.language == 'java-kotlin'
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java_version }}
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      if: inputs.language == 'java-kotlin'
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false

    # === Python Setup ===
    - name: Set up Python
      if: inputs.language == 'python'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'pip'

    - name: Install Python dependencies
      if: inputs.language == 'python'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        # TODO: Uncomment and configure based on your dependency manager
        # pip install -r requirements.txt
        # OR for Poetry:
        # curl -sSL https://install.python-poetry.org | python3 -
        # poetry install --no-interaction --no-ansi
