name: 'Setup AWS Credentials'
description: 'Configure AWS credentials using OIDC'
inputs:
  role_to_assume:
    description: 'AWS IAM role ARN to assume'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
  role_session_name:
    description: 'Role session name'
    required: false
    default: 'gh-actions'
runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role_to_assume }}
        role-session-name: ${{ inputs.role_session_name }}
        aws-region: ${{ inputs.aws_region }}
