name: Deploy PROD (ECS - Trunk-Based - Release)

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy (e.g., v1.2.3). Leave empty to use latest tag."
        required: false
        type: string
        default: ""

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ### General
  ENVIRONMENT: prod
  GITHUB_SHA: ${{ github.sha }}

  ### AWS Configuration
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID_PROD }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}

  ### ECS Configuration
  # TODO: Update these values based on your project
  ECS_CLUSTER_NAME: ${{ vars.ECS_CLUSTER_NAME_PROD }}
  SERVICE_NAME: ${{ vars.SERVICE_NAME_PROD }}
  TASK_FAMILY: ${{ vars.TASK_FAMILY_PROD }}
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}

  ### Docker Configuration
  DOCKER_REPO: ${{ vars.DOCKER_REPO }}
  BASE_DOMAIN: ${{ vars.BASE_DOMAIN_PROD }}

  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to PROD (ECS)

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v2
        id: github-app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Determine tag to use
        id: tag
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
              TAG="${{ github.event.inputs.tag }}"
          else
              # Extract tag from github.ref (e.g., refs/tags/v1.2.3 -> v1.2.3)
              TAG=${GITHUB_REF#refs/tags/}
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Using tag: $TAG"

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          ref: ${{ steps.tag.outputs.tag }}
          token: ${{ steps.github-app-token.outputs.token }}
          persist-credentials: false

      - name: "Install AWS CLI"
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: gh-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Prepare docker image tags
        run: |
          TAG_SHA=$(git rev-parse ${{ steps.tag.outputs.tag }})
          IMAGE_TAG=$(echo $TAG_SHA | cut -c1-8)
          PROD_TAG="prod-${IMAGE_TAG}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "PROD_TAG=$PROD_TAG" >> $GITHUB_ENV

      # TODO: Promote image from DEV to PROD by retagging
      # Option 1: If using same ECR repo, retag the DEV image
      # - name: Retag DEV image for PROD
      #   run: |
      #     # Get the latest DEV image tag
      #     DEV_IMAGE_TAG=$(aws ecr describe-images --repository-name ${{ env.DOCKER_REPO }} --region ${{ env.AWS_REGION }} \
      #       --query 'sort_by(imageDetails,&imagePushedAt)[-1].imageTags[0]' --output text | grep development || echo "")
      #     
      #     if [ -n "$DEV_IMAGE_TAG" ]; then
      #       # Retag the DEV image with PROD tag
      #       MANIFEST=$(aws ecr batch-get-image --repository-name ${{ env.DOCKER_REPO }} \
      #         --image-ids imageTag=$DEV_IMAGE_TAG --region ${{ env.AWS_REGION }} \
      #         --query 'images[0].imageManifest' --output text)
      #       
      #       aws ecr put-image --repository-name ${{ env.DOCKER_REPO }} \
      #         --image-tag ${{ env.PROD_TAG }} --image-manifest "$MANIFEST" --region ${{ env.AWS_REGION }}
      #     fi

      # Option 2: Build new image from tag (if needed)
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      #
      # - name: Build and Push the Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: Dockerfile
      #     tags: |
      #       ${{ env.DOCKER_REPO }}:${{ env.PROD_TAG }}
      #     push: true

      - name: Create new task definition
        run: |
          TASK_DEF_JSON=$(aws ecs describe-task-definition --task-definition "$TASK_FAMILY" --region "$AWS_REGION")
          NEW_TASK_DEF=$(echo "$TASK_DEF_JSON" | jq --arg IMAGE "$DOCKER_REPO:${{ env.PROD_TAG }}" '
              .taskDefinition
              | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)
              | (.containerDefinitions[] | select(.name=="'$CONTAINER_NAME'" )).image = $IMAGE
            ')
          echo "$NEW_TASK_DEF" > new-task-def.json
          TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json --region "$AWS_REGION" | jq -r '.taskDefinition.taskDefinitionArn')
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Trigger ECS deployment
        run: |
          aws ecs update-service \
              --region "$AWS_REGION" \
              --cluster "$ECS_CLUSTER_NAME" \
              --service "$SERVICE_NAME" \
              --task-definition "$TASK_DEF_ARN"

      - name: Send Notification
        if: always()
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ job.status == 'success' && ':rocket:' || ':x:' }} *${{ env.SERVICE_NAME }} - Deploy to ${{ env.ENVIRONMENT }} (ECS)* — *${{ job.status == 'success' && 'SUCCESS' || 'FAILURE' }}*"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Tag:* `${{ steps.tag.outputs.tag }}`\n*Environment:* ${{ env.ENVIRONMENT }}"
                      }
                    },
                    {
                      "type": "actions",
                      "elements": [
                        {
                          "type": "button",
                          "text": { "type": "plain_text", "text": "View Run" },
                          "style": "primary",
                          "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
