name: 'Deploy to ECS'
description: 'Deploy application to AWS ECS'
inputs:
  aws_region:
    description: 'AWS region'
    required: true
  ecs_cluster_name:
    description: 'ECS cluster name'
    required: true
  service_name:
    description: 'ECS service name'
    required: true
  task_family:
    description: 'ECS task family'
    required: true
  container_name:
    description: 'Container name in task definition'
    required: true
  image_uri:
    description: 'Docker image URI with tag'
    required: true
outputs:
  task_def_arn:
    description: 'Registered task definition ARN'
    value: ${{ steps.create-task-def.outputs.task_def_arn }}
runs:
  using: 'composite'
  steps:
    - name: Install AWS CLI
      shell: bash
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version

    - name: Create new task definition
      id: create-task-def
      shell: bash
      run: |
        TASK_DEF_JSON=$(aws ecs describe-task-definition --task-definition "${{ inputs.task_family }}" --region "${{ inputs.aws_region }}")
        NEW_TASK_DEF=$(echo "$TASK_DEF_JSON" | jq --arg IMAGE "${{ inputs.image_uri }}" '
            .taskDefinition
            | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)
            | (.containerDefinitions[] | select(.name=="${{ inputs.container_name }}" )).image = $IMAGE
          ')
        echo "$NEW_TASK_DEF" > new-task-def.json
        TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json --region "${{ inputs.aws_region }}" | jq -r '.taskDefinition.taskDefinitionArn')
        echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
        echo "task_def_arn=$TASK_DEF_ARN" >> $GITHUB_OUTPUT

    - name: Trigger ECS deployment
      shell: bash
      run: |
        aws ecs update-service \
            --region "${{ inputs.aws_region }}" \
            --cluster "${{ inputs.ecs_cluster_name }}" \
            --service "${{ inputs.service_name }}" \
            --task-definition "${{ steps.create-task-def.outputs.task_def_arn }}"
