name: Master build and (optional) Service health check

on:
  push:
    branches: ["master"]

permissions:
  id-token: write
  actions: write # required for cache write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ### General
  ENVIRONMENT: dev
  GITHUB_SHA: ${{ github.sha }}
  
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_DEV }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}

  ### Python version
  # TODO: Update Python version based on your project
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App Token
        id: github-app-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ vars.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: "Checkout source"
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          token: ${{ steps.github-app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: gh-actions
          aws-region: ${{ vars.AWS_REGION }}

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip' # or 'poetry' if using Poetry

      # TODO: Choose one of the following based on your dependency manager:
      # Option 1: Using pip
      # - name: "Install dependencies"
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      #
      # Option 2: Using Poetry
      # - name: "Install Poetry"
      #   uses: snok/install-poetry@v1
      #   with:
      #     version: latest
      #     virtualenvs-create: true
      #     virtualenvs-in-project: true
      #
      # - name: "Install dependencies"
      #   run: poetry install --no-interaction --no-ansi

      - name: "Run build"
        run: |
          # TODO: Add any build steps (e.g., compile, package, etc.)
          echo "Add your build commands here"

      # TODO: Consider removing if not necessary
      - name: "Run health-check test"
        run: |
          # TODO: Update based on your testing framework
          # Example:
          # pytest --fail-fast -m health_test
          echo "Add your health check test commands here"
        env:
          # TODO: Update these environment variables based on your project requirements
          DB_HOST: localhost
          DB_PORT: 5432
          REDIS_HOSTS: "localhost:6379,localhost:6380,localhost:6381,localhost:6382,localhost:6383,localhost:6384"
          IS_ON_AWS: true

      - name: "Upload test report"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: '**/test-results/**' # TODO: Update path based on your test framework output
