name: Deploy DEV (Trunk-Based - Release)

on:
  push:
    branches: ['release/*']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ### General
  ENVIRONMENT: dev
  GITHUB_SHA: ${{ github.sha }}

  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_DEV }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}

  ### Artifact registry
  # TODO: Update these values based on your project
  ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_URL }}
  ARTIFACTORY_USERNAME: ${{ vars.ARTIFACTORY_USERNAME }}
  AWS_CODE_ARTIFACT_DOMAIN: ${{ vars.AWS_CODE_ARTIFACT_DOMAIN_DEV }}

  ### Docker registry
  # TODO: Update these values based on your project
  DOCKER_REPO: ${{ vars.DOCKER_REPO_DEV }}
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY_DEV }}

  ### Helm values
  # TODO: Update these values based on your project
  HELM_REPO: ${{ vars.HELM_REPO }}
  HELM_SPARTAN_VERSION: ${{ vars.HELM_SPARTAN_VERSION }}
  SERVICE_NAME: ${{ vars.SERVICE_NAME }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  JAVA_VERSION: 17

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to DEV

    steps:
      - name: Generate GitHub App Token
        id: github-app-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ vars.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: "Checkout source"
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          token: ${{ steps.github-app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: gh-actions
          aws-region: ${{ vars.AWS_REGION }}

      - name: "Added Maven Artifact Registry to gradle.properties"
        run: |
          mkdir -p ~/.gradle
          cat <<EOF > ~/.gradle/gradle.properties
          artifactRegistryMavenReleaseUrl=${{ env.ARTIFACTORY_URL }}
          artifactRegistryMavenUsername=${{ env.ARTIFACTORY_USERNAME }}
          artifactRegistryMavenPassword=$(aws codeartifact get-authorization-token --domain $AWS_CODE_ARTIFACT_DOMAIN --domain-owner $AWS_ACCOUNT_ID --region $AWS_REGION --query authorizationToken --output text)
          EOF

      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: gradle

      # attempt to read cache from `master` branch only, should not write cache to `release/*` branches
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v4

      # TODO: Update or remove this step based on your project structure
      - name: "Execute Gradle build on module-postgresql"
        run: ./gradlew --build-cache :app:module-postgresql:panda --scan

      - name: "Execute full Gradle build"
        run: ./gradlew --build-cache build -x test --scan

      - name: "Login to Amazon ECR"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: "Extract app version from manifest.json"
        run: |
          APP_VERSION=$(cat manifest.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[ ",]//g'
          )
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV

      - name: "Prepare docker image tags"
        id: prepare_image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      # TODO: Update Docker image build steps based on your project structure
      - name: "Build and Push the main Docker image"
        uses: docker/build-push-action@v6
        with:
          context: ./app/api
          file: ./app/api/Dockerfile
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
          tags: ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}
          push: true

      - name: "Build and Push the migration Docker image"
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.migration
          tags: ${{ env.DOCKER_REPO }}-migration:${{ env.IMAGE_TAG }}
          push: true

      - name: "Build and Push the worker Docker image"
        uses: docker/build-push-action@v6
        with:
          context: ./app/worker
          file: ./app/worker/Dockerfile
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
          tags: ${{ env.DOCKER_REGISTRY }}/worker-rental:${{ env.IMAGE_TAG }}
          push: true
          
      - name: "Helm Install"
        run: |
          helm repo add spartan https://${{ env.GITHUB_TOKEN }}@${{ env.HELM_REPO }}
          helm upgrade --install --wait --timeout 600s ${{ env.SERVICE_NAME }}-deployment spartan/spartan --create-namespace -n $NAMESPACE -f k8s/${{ env.ENVIRONMENT }}/service-rental/values.yaml --version ${{ env.HELM_SPARTAN_VERSION }}
        env:
          NAMESPACE: ${{ env.SERVICE_NAME }}-${{ env.ENVIRONMENT }}
