name: 'Build and Push Docker Image'
description: 'Build and push Docker image to ECR'
inputs:
  context:
    description: 'Docker build context path'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  image_repo:
    description: 'ECR repository URI'
    required: true
  image_tag:
    description: 'Image tag'
    required: true
  build_args:
    description: 'Build arguments (newline-separated)'
    required: false
    default: ''
  push:
    description: 'Whether to push the image'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push the Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        tags: ${{ inputs.image_repo }}:${{ inputs.image_tag }}
        build-args: ${{ inputs.build_args != '' && inputs.build_args || '' }}
        push: ${{ inputs.push }}
