name: E2E Tests

permissions:
  contents: read
  pull-requests: write

on:
  # Run on merge to main/master
  push:
    branches: [ main, master ]

  # Allow manual triggering on any branch
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to test (leave empty to use current branch)"
        required: false
        type: string
        default: ""

  # Can be called from other workflows (like release)
  workflow_call:
    outputs:
      tests_passed:
        description: "Whether tests passed"
        value: ${{ jobs.e2e.outputs.result }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      result: ${{ steps.result.outputs.status }}
      summary: ${{ steps.test-summary.outputs.summary }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref }}

      - name: Display branch info
        run: |
          echo "🔀 Testing branch: ${{ inputs.branch || github.ref }}"
          echo "📝 Commit: $(git rev-parse --short HEAD)"
          echo "👤 Triggered by: ${{ github.actor }}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # TODO: Update Node.js version
          node-version: "24"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Build application
        run: yarn build
        env:
          NODE_ENV: production
          # TODO: Update environment variables based on your project
          # API endpoints (from GitHub Variables)
          # NEXT_PUBLIC_API_BASE_URL: ${{ vars.E2E_API_BASE_URL }}
          # NEXT_PUBLIC_BASE_WS_URL: ${{ vars.E2E_WS_BASE_URL }}
          # Optional: Application integration URL if needed
          # NEXT_PUBLIC_APPLICATION_INTEGRATION_URL: ${{ secrets.E2E_APPLICATION_INTEGRATION_URL }}
          # PostHog for feature flags (use dev environment)
          # NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.E2E_POSTHOG_KEY }}
          # NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.E2E_POSTHOG_HOST }}
          # Disable analytics/tracking
          # NEXT_PUBLIC_DATADOG_CLIENT_TOKEN: ""
          # NEXT_PUBLIC_INTERCOM_APP_ID: ""
          # NEXT_PUBLIC_CHATWOOT_WEBSITE_TOKEN: ""

      - name: Run Playwright tests
        id: playwright
        shell: bash
        run: |
          set -o pipefail
          npx playwright test --reporter=json,html 2>&1 | tee playwright-output.txt
        env:
          CI: true
          # TODO: Update auth credentials and test configuration
          # E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
          # E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
          # Test configuration (from GitHub Variables)
          # E2E_TEST_FOLDER: ${{ vars.E2E_TEST_FOLDER }}
          # E2E_TEST_SMART_SHEET: ${{ vars.E2E_TEST_SMART_SHEET }}
          # E2E_TEST_REPORT_COLUMN: ${{ vars.E2E_TEST_REPORT_COLUMN }}
          # E2E_TEST_REPORT_QUESTION: ${{ vars.E2E_TEST_REPORT_QUESTION }}
        continue-on-error: true

      - name: Parse test results
        id: test-summary
        if: always()
        run: |
          if [ -f "playwright-output.txt" ]; then
            SUMMARY=$(grep -E "^\s*\d+ (passed|failed)" playwright-output.txt | tail -1 || echo "No results found")
            echo "summary=$SUMMARY" >> $GITHUB_OUTPUT
          else
            echo "summary=Tests did not run" >> $GITHUB_OUTPUT
          fi

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 7

      - name: Set result output
        id: result
        if: always()
        run: |
          if [[ "${{ steps.playwright.outcome }}" == "success" ]]; then
            echo "status=passed" >> $GITHUB_OUTPUT
          else
            echo "status=failed" >> $GITHUB_OUTPUT
          fi

      - name: Fail job if tests failed
        if: steps.playwright.outcome == 'failure'
        run: exit 1

  # Post results to the merged PR
  post-results:
    name: Post Results to PR
    needs: e2e
    runs-on: ubuntu-latest
    if: always() && github.event_name == 'push'

    steps:
      - name: Find PR
        id: find-pr
        uses: actions/github-script@v7
        with:
          script: |
            // First, try to find PR by commit (works for merged PRs)
            const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
            });

            // Prefer merged PR, then open PR
            const mergedPR = prs.find(pr => pr.merged_at);
            const openPR = prs.find(pr => pr.state === 'open');
            const pr = mergedPR || openPR;

            if (pr) {
              console.log(`Found PR #${pr.number}: ${pr.title} (${pr.merged_at ? 'merged' : 'open'})`);
              core.setOutput('pr_number', pr.number.toString());
              core.setOutput('found', 'true');
            } else {
              // Fallback: try to find open PR for this branch
              const branch = context.ref.replace('refs/heads/', '');
              console.log(`No PR found by commit, searching for open PR on branch: ${branch}`);
            
              const { data: branchPRs } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: `${context.repo.owner}:${branch}`,
                state: 'open',
              });
            
              if (branchPRs.length > 0) {
                const branchPR = branchPRs[0];
                console.log(`Found open PR #${branchPR.number} for branch ${branch}`);
                core.setOutput('pr_number', branchPR.number.toString());
                core.setOutput('found', 'true');
              } else {
                console.log('No PR found for this commit or branch');
                core.setOutput('pr_number', '0');
                core.setOutput('found', 'false');
              }
            }

      - name: Post success comment
        if: steps.find-pr.outputs.found == 'true' && needs.e2e.outputs.result == 'passed'
        uses: actions/github-script@v7
        with:
          script: |
            const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const summary = `${{ needs.e2e.outputs.summary }}` || 'All tests passed';
            const prNumber = parseInt('${{ steps.find-pr.outputs.pr_number }}', 10);

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `## ✅ E2E Tests Passed\n\n${summary}\n\n[View full report](${runUrl})\n\n*Tested on commit \`${context.sha.substring(0, 7)}\`*`
            });

      - name: Post failure comment
        if: steps.find-pr.outputs.found == 'true' && needs.e2e.outputs.result == 'failed'
        uses: actions/github-script@v7
        with:
          script: |
            const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const summary = `${{ needs.e2e.outputs.summary }}` || 'Tests failed';
            const prNumber = parseInt('${{ steps.find-pr.outputs.pr_number }}', 10);
            const actor = '${{ github.actor }}';

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `## ❌ E2E Tests Failed\n\n${summary}\n\n[View full report and artifacts](${runUrl})\n\n*Tested on commit \`${context.sha.substring(0, 7)}\`*\n\ncc @${actor}`
            });

  # Notify Slack on test results (optional)
  slack-notification:
    name: Slack Notification
    needs: e2e
    runs-on: ubuntu-latest
    if: always() && github.event_name == 'push'
    env:
      # TODO: Configure Slack webhook URL
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_E2E_WEBHOOK_URL }}

    steps:
      - name: Check if Slack webhook is configured
        id: check-slack
        run: |
          if [ -n "$SLACK_WEBHOOK_URL" ]; then
            echo "configured=true" >> $GITHUB_OUTPUT
          else
            echo "configured=false" >> $GITHUB_OUTPUT
            echo "::notice::Slack webhook not configured, skipping notification"
          fi

      - name: Find PR
        if: steps.check-slack.outputs.configured == 'true'
        id: find-pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
            });

            const mergedPR = prs.find(pr => pr.merged_at);
            const openPR = prs.find(pr => pr.state === 'open');
            let pr = mergedPR || openPR;

            // Fallback: try to find open PR for this branch
            if (!pr) {
              const branch = context.ref.replace('refs/heads/', '');
              const { data: branchPRs } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: `${context.repo.owner}:${branch}`,
                state: 'open',
              });
              if (branchPRs.length > 0) {
                pr = branchPRs[0];
              }
            }

            if (pr) {
              core.setOutput('pr_number', pr.number.toString());
              core.setOutput('pr_title', pr.title);
              core.setOutput('pr_url', pr.html_url);
              core.setOutput('found', 'true');
            } else {
              core.setOutput('pr_url', `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/commit/${context.sha}`);
              core.setOutput('found', 'false');
            }

      - name: Send Slack notification (Success)
        if: steps.check-slack.outputs.configured == 'true' && needs.e2e.outputs.result == 'passed'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "✅ E2E Tests Passed",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n`${{ github.ref_name }}`"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n`${{ github.sha }}`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${{ github.actor }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Summary:*\n${{ needs.e2e.outputs.summary || 'All tests passed' }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Workflow Run",
                        "emoji": true
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "style": "primary"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View PR",
                        "emoji": true
                      },
                      "url": "${{ steps.find-pr.outputs.pr_url }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Send Slack notification (Failure)
        if: steps.check-slack.outputs.configured == 'true' && needs.e2e.outputs.result == 'failed'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "❌ E2E Tests Failed",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n`${{ github.ref_name }}`"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n`${{ github.sha }}`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${{ github.actor }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Summary:*\n${{ needs.e2e.outputs.summary || 'Tests failed' }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Workflow Run",
                        "emoji": true
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "style": "danger"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View PR",
                        "emoji": true
                      },
                      "url": "${{ steps.find-pr.outputs.pr_url }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
