name: Master build and (optional) Service health check

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write
  actions: write # required for cache write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ### General
  ENVIRONMENT: dev
  GITHUB_SHA: ${{ github.sha }}
  
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_DEV }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}

  ### Python version
  # TODO: Update Python version based on your project
  PYTHON_VERSION: '3.11'

jobs:
  build:
    # TODO: Use self-hosted runner for resource-intensive builds (e.g., runs-on: builder-16-32)
    runs-on: ubuntu-latest

    steps:
      # === Step 1: Build and Test ===
      - uses: ./.github/actions/build-and-test
        with:
          app_id: ${{ vars.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          ref: ${{ github.ref }}
          aws_role_to_assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ env.AWS_REGION }}
          language: 'python'
          python_version: ${{ env.PYTHON_VERSION }}
          build_command: |
            # TODO: Add any build steps (e.g., compile, package, etc.)
            echo "Add your build commands here"
          test_command: |
            # TODO: Update based on your testing framework
            # Example: pytest --fail-fast -m health_test
            echo "Add your health check test commands here"
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          REDIS_HOSTS: "localhost:6379,localhost:6380,localhost:6381,localhost:6382,localhost:6383,localhost:6384"
          IS_ON_AWS: true

      - name: "Upload test report"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: '**/test-results/**' # TODO: Update path based on your test framework output
