name: PR

# === Workflow Description ===
# This workflow runs build and tests for Python backend pull requests.
# It ensures code quality and catches errors before merging.
# Triggers: Pull request events.

on:
  pull_request:

permissions:
  id-token: write
  actions: write # required for cache write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # === General Configuration ===
  ENVIRONMENT: dev
  GITHUB_SHA: ${{ github.sha }}

  # === AWS Configuration ===
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_DEV }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}

  # === Language Configuration ===
  # TODO: Update Python version based on your project
  PYTHON_VERSION: '3.11'

jobs:
  pr:
    # TODO: Use self-hosted runner for resource-intensive builds (e.g., runs-on: builder-16-32)
    runs-on: ubuntu-latest

    steps:
      # === Step 1: Build and Test ===
      - uses: ./.github/actions/build-and-test
        with:
          app_id: ${{ vars.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          ref: ${{ github.head_ref }}
          aws_role_to_assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ env.AWS_REGION }}
          language: 'python'
          python_version: ${{ env.PYTHON_VERSION }}
          lint_command: |
            # TODO: Update based on your linting tools (e.g., ruff, black, flake8, pylint)
            # Example: ruff check . && black --check .
            echo "Add your linting commands here"
          run_linters: 'true'
          test_command: |
            # TODO: Update based on your testing framework (e.g., pytest, unittest)
            # Example: pytest --cov --cov-report=xml
            echo "Add your test commands here"
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          REDIS_HOSTS: "localhost:6379,localhost:6380,localhost:6381,localhost:6382,localhost:6383,localhost:6384"
