name: Deploy PROD (Matrix - EKS - Normal - Main/Master) - Python

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ### General
  GITHUB_SHA: ${{ github.sha }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  GH_APP_ID: ${{ vars.GH_APP_ID }}
  GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}

  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_TO_ASSUME_DEV: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}

  ### Docker registry
  # TODO: Update these values based on your project
  DOCKER_REPO_DEV: ${{ vars.DOCKER_REPO_DEV }}
  DOCKER_REGISTRY_DEV: ${{ vars.DOCKER_REGISTRY_DEV }}

  ### Helm values
  # TODO: Update these values based on your project
  HELM_REPO: ${{ vars.HELM_REPO }}
  HELM_SPARTAN_VERSION: ${{ vars.HELM_SPARTAN_VERSION }}
  SERVICE_NAME: ${{ vars.SERVICE_NAME }}

jobs:
  promote-images:
    outputs:
      IMAGE_TAG: ${{ steps.prepare_image.outputs.app_version }}
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App Token
        id: github-app-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ vars.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: "Checkout source"
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          token: ${{ steps.github-app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: "Configure AWS Credentials DEV"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME_DEV }}
          role-session-name: gh-actions
          aws-region: ${{ vars.AWS_REGION }}

      - name: "Login to Amazon ECR"
        id: login-ecr-dev
        uses: aws-actions/amazon-ecr-login@v2

      - name: "Extract app version"
        id: prepare_image
        run: |
          # TODO: Update based on your Python project versioning
          # Option 1: Read from pyproject.toml or setup.py
          # APP_VERSION=$(grep -m 1 "version" pyproject.toml | cut -d'"' -f2)
          # Option 2: Use git tag
          APP_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "dev-${GITHUB_SHA::8}")
          
          echo $APP_VERSION
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV
          echo "app_version=${APP_VERSION}" >> $GITHUB_OUTPUT

      - name: "Prepare Docker DEV image tags"
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      # TODO: Update Docker image pull steps based on your project structure
      - name: Pull image from Dev ECR
        run: |
          docker pull ${{ env.DOCKER_REPO_DEV }}:$IMAGE_TAG
          docker pull ${{ env.DOCKER_REPO_DEV }}-migration:$IMAGE_TAG
          docker pull ${{ env.DOCKER_REGISTRY_DEV }}/worker-rental:$IMAGE_TAG

      - name: Logout from Dev ECR
        run: |
          docker logout

  deploy:
    needs: promote-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [prod-1, prod-2, prod-3]
      fail-fast: false

    name: Deploy to ${{ matrix.environment }}

    steps:
      - name: Generate GitHub App Token
        id: github-app-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ vars.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: "Checkout source"
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          token: ${{ steps.github-app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}
          role-session-name: gh-actions
          aws-region: ${{ vars.AWS_REGION }}

      - name: "Login to Amazon ECR"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Retag and push image for ${{ matrix.environment }}
        run: |
          # TODO: Update these based on your ECR repository structure
          # Option 1: Use same repo with environment-specific tags
          docker tag \
          ${{ env.DOCKER_REPO_DEV }}:${{ needs.promote-images.outputs.IMAGE_TAG }} \
          ${{ vars.DOCKER_REPO_PROD }}:${{ needs.promote-images.outputs.IMAGE_TAG }}-${{ matrix.environment }}
          
          docker push ${{ vars.DOCKER_REPO_PROD }}:${{ needs.promote-images.outputs.IMAGE_TAG }}-${{ matrix.environment }}
          
          # Option 2: Use environment-specific repos
          # docker tag \
          # ${{ env.DOCKER_REPO_DEV }}:${{ needs.promote-images.outputs.IMAGE_TAG }} \
          # ${{ vars.DOCKER_REPO_PROD }}-${{ matrix.environment }}:${{ needs.promote-images.outputs.IMAGE_TAG }}
          # 
          # docker push ${{ vars.DOCKER_REPO_PROD }}-${{ matrix.environment }}:${{ needs.promote-images.outputs.IMAGE_TAG }}

      - name: "Helm Install to ${{ matrix.environment }}"
        run: |
          helm repo add spartan https://${{ vars.GITHUB_TOKEN }}@${{ env.HELM_REPO }}
          helm upgrade --install --wait --timeout 600s \
            ${{ env.SERVICE_NAME }}-deployment-${{ matrix.environment }} \
            spartan/spartan \
            --create-namespace \
            -n ${{ env.SERVICE_NAME }}-${{ matrix.environment }} \
            -f k8s/${{ matrix.environment }}/${{ env.SERVICE_NAME }}/values.yaml \
            --version ${{ env.HELM_SPARTAN_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update deployment badge
        run: |
          mkdir -p .github/badges
          echo "{\"schemaVersion\": 1, "label\": \"${{ matrix.environment }}\", \"message\": \"${{ needs.promote-images.outputs.IMAGE_TAG }}\"}}" > .github/badges/${{ matrix.environment }}.json
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/badges/${{ matrix.environment }}.json
          git commit -m "Update deployment badge for ${{ matrix.environment }}" || exit 0
          git push || exit 0
        run: |
          mkdir -p .github/badges
          echo "{\"schemaVersion\": 1, \"label\": \"${{ matrix.environment }}\", \"message\": \"${{ needs.promote-images.outputs.IMAGE_TAG }}\"}" > .github/badges/${{ matrix.environment }}.json

      - name: Send Notification
        if: always() && needs.deploy.result == 'success'
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ job.status == 'success' && ':rocket:' || ':x:' }} *${{ env.SERVICE_NAME }} - Deploy to ${{ matrix.environment }} (EKS)* — *${{ job.status == 'success' && 'SUCCESS' || 'FAILURE' }}*"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Version:* `${{ needs.promote-images.outputs.IMAGE_TAG }}`\n*Environment:* ${{ matrix.environment }}"
                      }
                    },
                    {
                      "type": "actions",
                      "elements": [
                        {
                          "type": "button",
                          "text": { "type": "plain_text", "text": "View Run" },
                          "style": "primary",
                          "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  publish-badges:
    needs: [promote-images, deploy]
    if: always() && needs.deploy.result == 'success'
    uses: ./.github/workflows/publish-badges.yml
    with:
