name: PR

# === Workflow Description ===
# This workflow runs build and tests for Kotlin/Java backend pull requests.
# It ensures code quality and catches errors before merging.
# Triggers: Pull request events.

on:
  pull_request:

permissions:
  id-token: write
  actions: write # required for cache write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # === General Configuration ===
  ENVIRONMENT: dev
  GITHUB_SHA: ${{ github.sha }}

  # === AWS Configuration ===
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_DEV }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}

  # === Artifact Registry ===
  # TODO: Update these values based on your project
  ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_URL }}
  ARTIFACTORY_USERNAME: ${{ vars.ARTIFACTORY_USERNAME }}
  AWS_CODE_ARTIFACT_DOMAIN: ${{ vars.AWS_CODE_ARTIFACT_DOMAIN_DEV }}
  
  # === Language Configuration ===
  JAVA_VERSION: 17

jobs:
  pr:
    # TODO: Use self-hosted runner for resource-intensive builds (e.g., runs-on: builder-16-32)
    runs-on: builder-16-32

    steps:
      # === Step 1: Setup Flyway (for database migrations) ===
      - name: Install Flyway
        uses: red-gate/setup-flyway@v1
        with:
          architecture: 'java'

      - name: Set FLYWAY_DIR
        shell: bash
        run: |
          FLY_BIN=""
          for d in "$HOME"/_work/_tool/flyway/*/java "$HOME"/_work/_tool/flyway/*; do
            if [ -x "$d/flyway" ]; then FLY_BIN="$d/flyway"; break; fi
          done
          if [ -z "$FLY_BIN" ]; then
            echo "Could not locate Flyway binary" >&2
            exit 127
          fi
          echo "FLYWAY_DIR=$FLY_BIN" >> $GITHUB_ENV

      # === Step 2: Build and Test ===
      - uses: ./.github/actions/build-and-test
        with:
          app_id: ${{ vars.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          ref: ${{ github.head_ref }}
          aws_role_to_assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ env.AWS_REGION }}
          language: 'java-kotlin'
          java_version: ${{ env.JAVA_VERSION }}
          artifactory_url: ${{ env.ARTIFACTORY_URL }}
          artifactory_username: ${{ env.ARTIFACTORY_USERNAME }}
          aws_code_artifact_domain: ${{ env.AWS_CODE_ARTIFACT_DOMAIN }}
          aws_account_id: ${{ env.AWS_ACCOUNT_ID }}
          exclude_tests: 'true'
          test_command: './gradlew --build-cache test --fail-fast'
        env:
          FLYWAY_DIR: ${{ env.FLYWAY_DIR }}
          DB_HOST: localhost
          DB_PORT: 5432
          REDIS_HOSTS: "localhost:6379,localhost:6380,localhost:6381,localhost:6382,localhost:6383,localhost:6384"
