name: Deploy Prod (Amplify - Normal - Main/Master)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AMPLIFY_WEBHOOK_URL: ${{ secrets.AMPLIFY_WEBHOOK_URL_PROD }}

jobs:
  amplify_deploy:
    runs-on: ubuntu-latest
    name: Amplify Prod Deploy

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Generate GitHub App Token
        id: github-app-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ vars.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          token: ${{ steps.github-app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Trigger Amplify Deployment
        run: |
          curl -X POST -d {} '${{ env.AMPLIFY_WEBHOOK_URL }}&operation=startbuild' -H 'Content-Type:application/json'
